rabbitmq:
  host: 150.132.35.5
  port:
  user:
  password:
  exchange:
    name: eiffel.test
  tls:
spring:
  http.converters:
    preferred-json-mapper: gson
activedirectory:
  enabled: true
  domain:
  url:
